export const snippets = {
  Texto: '## Nuevo apartado\n\nEscribe aquí tu contenido.',
  Imagen: '![Descripción de la imagen](assets/imagen.png)',
  'Dos columnas': ':::columns\n### Primera columna\nContenido.\n---\n### Segunda columna\nContenido.\n:::',
  Quiz: ':::quiz\nquestion: ¿Cuál opción es correcta?\n- [ ] Opción A\n- [x] Opción B\n- [ ] Opción C\nfeedback: ¡Correcto!\n:::',
  'Verdadero/Falso': ':::truefalse\nquestion: Escribe una afirmación.\nanswer: true\nfeedback: Explica la respuesta.\n:::',
  Flashcards: ':::flashcards\n- Concepto | Definición\n- Ejemplo | Explicación\n:::',
  Tabs: ':::tabs\n- Teoría | Explicación teórica.\n- Ejemplo | Un ejemplo concreto.\n:::',
  Acordeón: ':::accordion\n- Pregunta 1 | Respuesta 1.\n- Pregunta 2 | Respuesta 2.\n:::',
  Ordenar: ':::sort\n- Primer paso\n- Segundo paso\n- Tercer paso\n:::',
  Relacionar: ':::match\n- Concepto A | Definición A\n- Concepto B | Definición B\n:::',
  Slider: ':::slider\nlabel: Nivel\nmin: 0\nmax: 100\nvalue: 50\n:::',
  Hotspot: ':::hotspot\nimage: assets/imagen.png\n- 25 | 40 | Punto A | Explicación del punto A\n- 70 | 60 | Punto B | Explicación del punto B\n:::',
  Mermaid: ':::mermaid\nflowchart LR\n  Usuario --> Interfaz\n  Interfaz --> Sistema\n:::',
  Código: '```js\nconsole.log("Hola, clase");\n```',
  Ecuación: '$$E = mc^2$$',
  Tabla: '| Concepto | Descripción |\n| --- | --- |\n| A | Primera idea |\n| B | Segunda idea |',
  Cita: '> Una cita memorable.\n\n— Autor',
  Timeline: ':::mermaid\ntimeline\n  title Evolución\n  2020 : Primera etapa\n  2024 : Segunda etapa\n:::',
  Iframe: ':::iframe\nurl: https://example.org/\n:::',
  'Mostrar respuesta': ':::answer\nEsta es la respuesta explicada.\n:::',
  Calculadora: ':::calculator\nlabel: Cantidad\nfactor: 2\nformula: Resultado\n:::',
  Formulario: ':::form\nquestion: Escribe una reflexión breve\n:::'
};
